// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3lvQP7jMw6vAfDSIdKn6xkl9j1noXyqA',
    appId: '1:681943279579:web:23c30c3d4871f559fce9fe',
    messagingSenderId: '681943279579',
    projectId: 'ecommerce-app-8904b',
    authDomain: 'ecommerce-app-8904b.firebaseapp.com',
    storageBucket: 'ecommerce-app-8904b.firebasestorage.app',
    measurementId: 'G-9FVWYM1REP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2VRgB8P545tTSLc8MFDKAy3PUmegM0r8',
    appId: '1:681943279579:android:1e82b6f0b2d984d4fce9fe',
    messagingSenderId: '681943279579',
    projectId: 'ecommerce-app-8904b',
    storageBucket: 'ecommerce-app-8904b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEp5TYYcM86RNyVsZ_GmESa5vVlOtw2AI',
    appId: '1:681943279579:ios:3d12adbc9a5a698ffce9fe',
    messagingSenderId: '681943279579',
    projectId: 'ecommerce-app-8904b',
    storageBucket: 'ecommerce-app-8904b.firebasestorage.app',
    iosBundleId: 'com.example.cwtStarterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3lvQP7jMw6vAfDSIdKn6xkl9j1noXyqA',
    appId: '1:681943279579:web:bc32954914ffc252fce9fe',
    messagingSenderId: '681943279579',
    projectId: 'ecommerce-app-8904b',
    authDomain: 'ecommerce-app-8904b.firebaseapp.com',
    storageBucket: 'ecommerce-app-8904b.firebasestorage.app',
    measurementId: 'G-9000CVVS4T',
  );
}
